name: PHPCPD

on:
  pull_request:
    branches:
      - develop
    paths:
      - '**.php'
      - '.github/workflows/phpcpd.yml'
  push:
    branches:
      - develop
    paths:
      - '**.php'
      - '.github/workflows/phpcpd.yml'

jobs:
  build:
    name: Code Copy-Paste Detection
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: phpcpd
          extensions: dom, mbstring
          coverage: none

      - name: Detect duplicate code
        run: phpcpd src/ tests/
